### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Georgitanev** [muschellij2/intro_to_r#3]
I saw that it happened in the video, but on my test it's not happening and I don't know why.
#the code

# 3. Use the `read_excel()` function in the `readxl` package to 
#		read in the dataset
destfile = file.path(tempdir(), "Monuments.xlsx")
download.file("http://johnmuschelli.com/intro_to_r/data/Monuments.xlsx", 
              destfile = destfile)
mon = read_excel(destfile)

#the error
> library(readxl)
> destfile = file.path(tempdir(), "Monuments.xlsx")
> download.file("http://johnmuschelli.com/intro_to_r/data/Monuments.xlsx", 
+               destfile = destfile)
trying URL 'http://johnmuschelli.com/intro_to_r/data/Monuments.xlsx'
Content type 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' length 14013 bytes (13 KB)
downloaded 13 KB

> mon = read_excel(destfile)
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Evaluation error: zip file 'C:\Users\G\AppData\Local\Temp\RtmpAjmis5/Monuments.xlsx' cannot be opened.
> mon = read_excel(destfile)
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Evaluation error: zip file 'C:\Users\G\AppData\Local\Temp\RtmpAjmis5/Monuments.xlsx' cannot be opened.
> library(readxl)
> library(readr)
> mon = read_excel(destfile)
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Evaluation error: zip file 'C:\Users\G\AppData\Local\Temp\RtmpAjmis5/Monuments.xlsx' cannot be opened.
>

**Comment by muschellij2** [comment]
There are problems on Windows machines with the download.file/unzip script
there.  Download Monuments.xlsx to your machine and then read from there.
It may also using `tempdir()`.

Try to change destfile = file.path(".", "Monuments.xlsx")

and rerun


John
