### ISSUE TITLE
clarify labs by adding backticks to what we want as R objects

### ISSUE THREAD

**Issue by andrewejaffe** [muschellij2/intro_to_r#6]
And also add parentheses to function names.
ie in data cleaning lab:

2.  Create a data set called namat which is equal to is.na(bike).  
What is the class of namat?  Run rowSums and colSums on namat.
These represent the number of missing values in the rows and columns of
bike.  Don't print rowSums, but do a table of the rowSums

Should be:

2.  Create a data set called `namat` which is equal to is.na(bike).  
What is the class of `namat`?  Run rowSums() and colSums() on `namat`.
These represent the number of missing values in the rows and columns of
`bike`.  Don't print rowSums(), but do a table() of the rowSums()

**Comment by muschellij2** [comment]
Is this pushed?

John
